### ISSUE TITLE
Add short problem description here 

### ISSUE THREAD

**Issue by barmakuks** [barmakuks/bezma#1]
Add reproduce steps here

**Comment by Jagraf** [comment]
Виталий, привет!

Пересылаю вам файл записи партии, где произошли описанные ниже события.

Матч до трех пунктов.
На втором ходу я сделал удвоение (дабл). И принял его со стороны противника. Через пару ходов я имитировал прерывание партии и просто закрыл и открыл программу, ничего не доске не меняя. Затем партия была продолжена и закончена с неожиданным итогом: вместо 2 очков, которые необходимо было засчитать победителю, почему-то было засчитано 4 и матч был закончен.

Проверьте, плиз. 

White_player-Black_player-3p-2015-08-19[1].txt

; [eventDate "2015.08.19"]
; [Black "White player"]
; [White "Black player"]

 3 point match

 Game 1
 White player : 0               Black player : 0  
  1) 13: 8/5 6/5                  14: 13/9 9/8 
  2)  Doubles => 2                 Takes
  3) 14: 13/9 6/5                 26: 24/22 22/16\* 
  4) 44: 25/21 24/20 13/9\* 13/9   56: 
  5) 15: 9/4 5/4                  11: 25/24 24/23 6/5\* 6/5 
  6) 56:                          16: 13/7 8/7 
  7) 44: 25/21 13/9 13/9 6/2\*     13: 25/22 24/23\* 
  8) 56:                          45: 22/18 18/13 
  9) 34: 25/21 24/21              15: 13/12 12/7 
 10) 26: 21/15 15/13              55: 23/18 18/13 13/8 8/3 
 11) 26: 21/15 15/13              26: 13/11 11/5 
 12) 15: 9/8 8/3                  15: 8/3 7/6 
 13) 15: 9/8 8/3                  45: 6/1 5/1 
 14) 36: 9/6 8/2                  44: 13/9 13/9 9/5 9/5 
 15) 56: 13/8 13/7                33: 8/5 8/5 5/2 5/2 
 16) 56: 8/3 8/2                  66: 7/1 7/1 6/0 6/0 
 17) 26: 21/19\* 19/13             15: 25/24 
 18) 15: 13/12 12/7               23: 5/3 5/2 
 19) 26: 21/19 19/13              34: 5/2 5/1 
 20) 16: 13/12 12/6               12: 3/1 2/1 
 21) 13: 6/5 5/2                  12: 3/1 2/1 
 22) 33: 7/4 7/4 4/1\* 4/1         16: 
 23) 26: 6/0 2/0                  16: 
 24) 26: 6/4 6/0                  15: 
 25) 34: 4/0 3/0                  15: 
 26) 16: 5/4 5/0                  56: 25/20 20/14 
 27) 22: 4/2 4/2 2/0 2/0          55: 14/9 9/4 4/0 3/0 
 28) 36: 4/0 3/0                  11: 1/0 1/0 1/0 1/0 
 29) 26: 3/0 2/0                  11: 2/1 2/1 1/0 1/0 
 30) 16: 2/0 1/0                  11: 1/0 1/0 1/0 1/0 
 31) 16: 1/0  
      Wins 4 points
